"""Tests for ORM model fields and the startup sweeper.

Covers:
  - Fix #1 (audit finding H1): Job.handoff_status enum field
  - Fix #2 (audit finding H2): JobRunner.sweep_stuck_jobs()
"""

from __future__ import annotations

from datetime import datetime, timedelta

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.models import (
    HandoffStatus,
    Job,
    JobStatus,
    ModuleRun,
    _now,
)


# ---------------------------------------------------------------------------
# Helpers — the Job table has a duplicate-index bug in the Finding model
# (both `index=True` on `source` AND an explicit `Index(...)`), so we build a
# file-backed engine with ONLY the Job + ModuleRun tables. This mirrors the
# pattern already in test_rate_limiter.py.
# ---------------------------------------------------------------------------


@pytest.fixture
def jobs_only_db(tmp_path):
    """Per-test sync DB session with only the Job table created."""
    db_path = tmp_path / "sweep_test.db"
    if db_path.exists():
        db_path.unlink()

    eng = create_engine(
        f"sqlite:///{db_path}",
        connect_args={"check_same_thread": False},
    )
    Job.__table__.create(bind=eng, checkfirst=True)
    ModuleRun.__table__.create(bind=eng, checkfirst=True)
    Session_ = sessionmaker(
        bind=eng, autoflush=False, autocommit=False, expire_on_commit=False
    )

    # Patch SessionLocal in both modules so JobRunner + helpers see this DB.
    import app.database as app_db
    import app.orchestrator.job_runner as jr_module

    original_app_session = app_db.SessionLocal
    original_jr_session = jr_module.SessionLocal
    app_db.SessionLocal = Session_
    jr_module.SessionLocal = Session_

    db = Session_()
    try:
        yield db
    finally:
        db.close()
        Job.__table__.drop(bind=eng, checkfirst=True)
        ModuleRun.__table__.drop(bind=eng, checkfirst=True)
        app_db.SessionLocal = original_app_session
        jr_module.SessionLocal = original_jr_session
        eng.dispose()
        try:
            db_path.unlink()
        except FileNotFoundError:
            pass


# ---------------------------------------------------------------------------
# Fix #1 — handoff_status field on Job
# ---------------------------------------------------------------------------


def test_job_default_handoff_status_is_not_generated(jobs_only_db) -> None:
    """A new Job has handoff_status=NOT_GENERATED by default after flush.

    Regression test for audit finding H1: previously handoff generation
    state was conflated with module errors via error_message overloading.

    Note: SQLAlchemy `default=` is a column-level default applied at
    INSERT/flush time, not at Python object construction. We verify the
    default by reading the row back from the DB.
    """
    db = jobs_only_db
    job = Job(target="example.com", selected_modules=[])
    db.add(job)
    db.commit()
    db.refresh(job)
    assert job.handoff_status == HandoffStatus.NOT_GENERATED


def test_job_handoff_status_can_be_set_to_pending() -> None:
    """handoff_status accepts PENDING."""
    job = Job(target="example.com", selected_modules=[])
    job.handoff_status = HandoffStatus.PENDING
    assert job.handoff_status == HandoffStatus.PENDING


def test_job_handoff_status_can_be_set_to_generated() -> None:
    """handoff_status accepts GENERATED."""
    job = Job(target="example.com", selected_modules=[])
    job.handoff_status = HandoffStatus.GENERATED
    assert job.handoff_status == HandoffStatus.GENERATED


def test_job_handoff_status_can_be_set_to_failed() -> None:
    """handoff_status accepts FAILED."""
    job = Job(target="example.com", selected_modules=[])
    job.handoff_status = HandoffStatus.FAILED
    assert job.handoff_status == HandoffStatus.FAILED


def test_job_handoff_status_persists_round_trip(jobs_only_db) -> None:
    """handoff_status is persisted to the DB and read back."""
    db = jobs_only_db
    job = Job(
        target="example.com",
        selected_modules=[],
        handoff_status=HandoffStatus.GENERATED,
    )
    db.add(job)
    db.commit()

    db.expire_all()
    loaded = db.get(Job, job.id)
    assert loaded is not None
    assert loaded.handoff_status == HandoffStatus.GENERATED


def test_handoff_status_enum_values_are_strings() -> None:
    """HandoffStatus inherits from str — values serialize as plain strings."""
    assert HandoffStatus.NOT_GENERATED.value == "not_generated"
    assert HandoffStatus.PENDING.value == "pending"
    assert HandoffStatus.GENERATED.value == "generated"
    assert HandoffStatus.FAILED.value == "failed"


# ---------------------------------------------------------------------------
# Fix #2 — JobRunner.sweep_stuck_jobs()
# ---------------------------------------------------------------------------


def _make_runner():
    """Build a minimal JobRunner — the sweeper doesn't need modules or AI."""
    from app.orchestrator.job_runner import JobRunner

    return JobRunner(module_registry={}, ai_validator=None)  # type: ignore[arg-type]


@pytest.mark.asyncio
async def test_sweep_marks_old_validating_jobs_failed(jobs_only_db) -> None:
    """A job stuck in VALIDATING for >max_age_minutes is marked FAILED.

    Regression test for audit finding H2: a crash between VALIDATING and
    COMPLETED would otherwise leave the job orphaned forever.
    """
    db = jobs_only_db

    # Job stuck in VALIDATING for 60 minutes (older than 30-min cutoff).
    stuck = Job(
        id="stuck-job-1",
        target="stuck.example.com",
        status=JobStatus.VALIDATING,
        selected_modules=[],
        started_at=_now() - timedelta(minutes=60),
    )
    db.add(stuck)
    db.commit()

    runner = _make_runner()
    count = await runner.sweep_stuck_jobs(max_age_minutes=30)

    assert count == 1
    db.expire_all()
    refreshed = db.get(Job, "stuck-job-1")
    assert refreshed is not None
    assert refreshed.status == JobStatus.FAILED
    assert refreshed.error_message is not None
    assert "startup sweeper" in refreshed.error_message
    assert "VALIDATING" in refreshed.error_message


@pytest.mark.asyncio
async def test_sweep_skips_recent_validating_jobs(jobs_only_db) -> None:
    """Jobs in VALIDATING for LESS than max_age_minutes are NOT swept.

    A job that's been validating for 5 minutes is probably mid-flight on
    a slow machine — we must not kill it.
    """
    db = jobs_only_db

    recent = Job(
        id="recent-job",
        target="recent.example.com",
        status=JobStatus.VALIDATING,
        selected_modules=[],
        started_at=_now() - timedelta(minutes=5),
    )
    db.add(recent)
    db.commit()

    runner = _make_runner()
    count = await runner.sweep_stuck_jobs(max_age_minutes=30)

    assert count == 0
    db.expire_all()
    refreshed = db.get(Job, "recent-job")
    assert refreshed.status == JobStatus.VALIDATING


@pytest.mark.asyncio
async def test_sweep_skips_non_validating_jobs(jobs_only_db) -> None:
    """COMPLETED / FAILED / CANCELLED jobs are NOT touched.

    The sweeper exists to recover VALIDATING orphans only. Touching a
    COMPLETED job would silently break completed-history reporting.
    """
    db = jobs_only_db

    completed = Job(
        id="completed-job",
        target="done.example.com",
        status=JobStatus.COMPLETED,
        selected_modules=[],
        started_at=_now() - timedelta(hours=2),
        completed_at=_now() - timedelta(hours=1),
    )
    failed = Job(
        id="failed-job",
        target="broken.example.com",
        status=JobStatus.FAILED,
        selected_modules=[],
        started_at=_now() - timedelta(hours=2),
        error_message="Original failure",
    )
    pending = Job(
        id="pending-job",
        target="queued.example.com",
        status=JobStatus.PENDING,
        selected_modules=[],
        started_at=_now() - timedelta(hours=2),
    )
    db.add_all([completed, failed, pending])
    db.commit()

    runner = _make_runner()
    count = await runner.sweep_stuck_jobs(max_age_minutes=30)
    assert count == 0

    db.expire_all()
    assert db.get(Job, "completed-job").status == JobStatus.COMPLETED
    assert db.get(Job, "failed-job").status == JobStatus.FAILED
    assert db.get(Job, "failed-job").error_message == "Original failure"
    assert db.get(Job, "pending-job").status == JobStatus.PENDING


@pytest.mark.asyncio
async def test_sweep_returns_zero_when_nothing_to_sweep(jobs_only_db) -> None:
    """sweep_stuck_jobs returns 0 on an empty DB (not None, not -1)."""
    runner = _make_runner()
    count = await runner.sweep_stuck_jobs(max_age_minutes=30)
    assert count == 0


@pytest.mark.asyncio
async def test_sweep_counts_multiple_stuck_jobs(jobs_only_db) -> None:
    """sweep_stuck_jobs returns the count of all jobs swept in one pass."""
    db = jobs_only_db

    for i in range(3):
        db.add(
            Job(
                id=f"stuck-{i}",
                target=f"stuck{i}.example.com",
                status=JobStatus.VALIDATING,
                selected_modules=[],
                started_at=_now() - timedelta(minutes=45),
            )
        )
    db.commit()

    runner = _make_runner()
    count = await runner.sweep_stuck_jobs(max_age_minutes=30)
    assert count == 3
    db.expire_all()
    for i in range(3):
        assert db.get(Job, f"stuck-{i}").status == JobStatus.FAILED


@pytest.mark.asyncio
async def test_sweep_respects_custom_max_age(jobs_only_db) -> None:
    """A job older than a TIGHTER cutoff IS swept; a looser cutoff skips it."""
    db = jobs_only_db

    job = Job(
        id="boundary-job",
        target="boundary.example.com",
        status=JobStatus.VALIDATING,
        selected_modules=[],
        started_at=_now() - timedelta(minutes=20),
    )
    db.add(job)
    db.commit()

    runner = _make_runner()

    # 20 min job is OLDER than 10-min cutoff → swept.
    count = await runner.sweep_stuck_jobs(max_age_minutes=10)
    assert count == 1
    db.expire_all()
    assert db.get(Job, "boundary-job").status == JobStatus.FAILED